name = "DrakanHex7"
author = "alexyzer"
version = "7.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14ef768852976a90d1910c20ce1c588c0d777a4f5c4a9cd84aa8bb4b060da577"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
