name = "DrakanHex7"
author = "alexyzer"
version = "7.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ef02bcd0f25f788afee9321ab354e52998113394ba00c2446823262bb2b1920"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
