name = "DrakanHex7"
author = "alexyzer"
version = "7.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96520233bfcfdfccc2eca17cc49aa990d95e6e2e3ecc3f6a39e3160d269367ed"

[versions]
forge = "47.4.18"
minecraft = "1.20.1"
